version: 2.1

jobs:
  build:
    docker:
      - image: maven:3-jdk-8
    environment:
      JAVA_TOOLS_OPTIONS: "-Xmx1024m -XX:MaxPermSize=256m"
    steps:
      - checkout
      - restore_cache:
          key: cache
      - run: mvn clean install
      - run: mvn install -Pdefault-first,default-second -Dgib.enabled=true
      - save_cache:
          key: cache
          paths:
            - ~/.m2
