version: 2.1

jobs:
  build:
    docker:
      - image: maven:3
#       - image: circleci/openjdk:8-jdk
#       - image: store/oracle/serverjre:8
#         auth:
#           username: ryanmdev
#           password: $DOCKERHUB_PASSWORD
    resource_class: large
    environment:
      MAVEN_OPTS: "-Xmx2048M"
    steps:
      - checkout
      - restore_cache:
          key: cache
#       - run:
#           name: Install Maven
#           command: |
#             MAVEN_VERSION=3.6.1
#             sudo curl -O https://www-us.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
#             sudo tar xzf apache-maven-${MAVEN_VERSION}-bin.tar.gz -C /usr/local
#             cd /usr/local
#             sudo ln -s apache-maven-${MAVEN_VERSION} maven
#             cd $HOME
#             echo 'export M2_HOME=/usr/local/maven' >> $BASH_ENV
#             echo 'export PATH=${M2_HOME}/bin:${PATH}' >> $BASH_ENV
      - run: mvn clean install
      - run: mvn install -Pdefault-first,default-second -Dgib.enabled=true
      - save_cache:
          key: cache
          paths:
            - ~/.m2
