version: 2.1

jobs:
  build:
#     machine:
#       image: ubuntu-1604:201903-01
    docker:
      - image: store/oracle/serverjre:8
        auth:
          username: ryanmdev
          password: $DOCKERHUB_PASSWORD
#       - image: openjdk:12-jdk-oracle
      #- image: maven:3-jdk-8
      # - image: openjdk:8-jdk
    # resource_class: large
    environment:
      MAVEN_OPTS: "-Xmx2048M -Xss128M -XX:+CMSClassUnloadingEnabled -XX:+UseG1GC -XX:-UseGCOverheadLimit"
    steps:
      - checkout
      - restore_cache:
          key: cache
#       - run:
#           name: Install deps
#           command: |
#             #
#             #sudo apt update && sudo apt install openjfx
#             curl -O https://www-us.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz
#             tar xzf apache-maven-3.6.1-bin.tar.gz -C /usr/local
#             cd /usr/local
#             ln -s apache-maven-3.6.1 maven
#             cd $HOME
#             echo 'export M2_HOME=/usr/local/maven' >> $BASH_ENV
#             echo 'export PATH=${M2_HOME}/bin:${PATH}' >> $BASH_ENV
#       - run: sudo apt update && sudo apt install openjfx
      - run: mvn clean install
      - run: mvn install -Pdefault-first,default-second -Dgib.enabled=true
      - save_cache:
          key: cache
          paths:
            - .autoconf
            - /home/circleci/.m2
