version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    environment:
      MAVEN_OPTS: "-Xmx2048M -Xss128M -XX:+CMSClassUnloadingEnabled -XX:+UseG1GC -XX:-UseGCOverheadLimit"
    steps:
      - checkout
      - restore_cache:
          key: cache
      - run:
          name: APT Update
          command: |
            #sudo apt update
            #sudo apt install oracle-java8-installer
      - run: mvn -q install -Pdefault-first,default-second -Dgib.enabled=true
      - save_cache:
          key: cache
          paths:
            - .autoconf
            - /home/circleci/.m2
